/**
 * The mazes the folding page shows — found offline, kept here.
 *
 * GENERATED by `.dev/probe-fold-designs.ts`. Do not edit: run the probe.
 *
 * The object never varies, so neither do these. A search takes seconds at
 * three cells across a face and the better part of half a minute at four,
 * which is not a wait to put in front of someone who opened a page; found
 * once, they cost a decode and a check. They are the best of many tries at
 * each ruling, ranked by the longest walk in the pose where it is shortest —
 * see the probe for why that is the measure.
 *
 * Found under the welding rule a builder needs rather than the one a walk
 * needs: a side buried against another cube agrees with whatever is on show on
 * top of it (`BuildSurfaceOptions.weld`), so no printed wall can ever peek
 * across a passage on the model.
 *
 * Each is a perfect maze in all six poses. The page checks that again as it
 * decodes, because a stored design is only as good as the surface it was found
 * on, and falls back to searching if it ever stops being true.
 */

import type { StoredDesign } from '../stored-design.ts';

export const INFINITY_CUBE_DESIGNS: readonly StoredDesign[] = [
  // 192 cells, walks 43-55
  { cells: 2, classCount: 256,
    open: '5XOg5UNL4mmqlpexqbvlnXExE4-h-enYLl1Xpe7SKls' },
  // 192 cells, walks 40-51
  { cells: 2, classCount: 256,
    open: 'FlWvNoKuKq50-b6kpLNGYXk0XJGqtVnetOWJMb1O2t4' },
  // 192 cells, walks 40-49
  { cells: 2, classCount: 256,
    open: 'TFRsNrhubblj9ZZGL6DM6rBtd-fiYoTMknkeuXYbsec' },
  // 192 cells, walks 40-51
  { cells: 2, classCount: 256,
    open: 'lEZcY9TlRu-qrY50xIbb6s6KnBkXzhnPrtDFXtfuzOc' },
  // 192 cells, walks 39-65
  { cells: 2, classCount: 256,
    open: '1FOi9Baec2V2ntmAI3Hdjp3LjqnnVR_L-IgmUutt4ck' },
  // 192 cells, walks 39-54
  { cells: 2, classCount: 256,
    open: 'ZUGscuy25WlWHV_FCWW-k-XchlhLpcbh-qU13u7epxk' },
  // 432 cells, walks 69-84
  { cells: 3, classCount: 672,
    open: 'dguKQ1dqbS0g5hbbWt41VdK500wxVvmJ1xGPgr4Mz3RfjpYje7PFbKacKjqrNzo6jXjg0uz4aQTp9mBEu5wby5vH4T6Nx6aXdElzuMZhuRPLjvEs' },
  // 432 cells, walks 66-91
  { cells: 3, classCount: 672,
    open: 'auSipg3DV4a3tEo7RbniHK5NSs56xrims6p6NbeYk9qWbPZo61gsx6qszD4-WnM4rYSf0ZpltjQbi1XV1p4zfmZ7jop6Jpe2XVOfz3M-sSOdVa22' },
  // 432 cells, walks 65-83
  { cells: 3, classCount: 672,
    open: 'lGk2I7TSFTvJzzBvYdsi1Y1vXDgTZmp0E5tcBl1c3DPXs9-c8nxsylXquPXReeOU6isdczab57Jipa60zJ6ZbQ_uUUkOWe50N3pmZmxqXirmTHkY' },
  // 432 cells, walks 65-92
  { cells: 3, classCount: 672,
    open: 'cXiyHsUTX8hbaqroWmMhN-HD7WJkY-El9iHOGhzPjFazEpe3ppm53mfGbVye5egkXbiqVLY6djh3u8TOjviI52YST5xZxefk9aj02X2Xde7M4elo' },
  // 432 cells, walks 63-80
  { cells: 3, classCount: 672,
    open: 'NmJNayTakdRS-lRVm8xs4T-8Sut47KOoM3rE1pRZBcTqYx47s3XO1G_h5caOqcIdDjsr2egmjzSnC9d72p7h6KvbNFYFhWKTtOnV7nGUz7JZZ66n' },
  // 432 cells, walks 63-87
  { cells: 3, classCount: 672,
    open: '3iFZzGQ2Ql226tFysfWVuDU50DIan22PAVO3pSV-4KFlVxuXnkYnC3daoxd5K1qWRsbqME48jLesiw5V2YubL9N5zMxwdlrssAW3rAO3NH5JN67b' },
  // 768 cells, walks 96-136
  { cells: 4, classCount: 1280,
    open: 'FnWZNxHE90ngFFqPYVUi07ODWvtTadtNKzB212xdUR8XHWajdeJxVF_j2qF5mWQ9SWldZI27Ck0lr9hbnTzXZlY5K67JrGnuRXRLi_K1FfW0NYM7WjPqPZrOlzSKlm1FTwdnbVjfmDc5i1jvC9A92Rta7Z1Urm7Lmlfo5Uh7grFHvHblbHaW8H5B-FrT8TV6aluT8mHV1mnz0r2YwVNtBw' },
  // 768 cells, walks 87-108
  { cells: 4, classCount: 1280,
    open: '5QFXcg7ORgaekippeM2nNcYbY_9gjpy2L2vEY35jI3OMo1oaOHOb9D6sH9psnmiXjZixO7I5RD9bi9rTOyu8yRqpXK-5K2Y_esAnz5nCFesfKTtyk5rlHXnau0SHTuNWrJ9AmnkRdscjPmqZOeUdPXamK3IlrZnskfLumKZ4Oq_yKZfKB5GmWtW1cbG15bVY7Y1jyc2OrtcZadWf8I2qRQ' },
  // 768 cells, walks 86-112
  { cells: 4, classCount: 1280,
    open: 'xx5GMHk1RsVWMJk0Lm481GYrrll8feFaO1G7XOEeNjE0jNacNd3VBzqp_AldjvPDHBx_ODmKd4hae8reefBM7clqWz-XlaX0U_DDCpttuWnNKkun36JWNu4KpYMVt8lgpVq1R-p6dctloY4bluQHnLgy2_zIJpvOfsyIdiar3Bp40lzGWtiawZlZeTqL7eQbbr7oOM4vc_dQg5yusVfmCw' },
  // 768 cells, walks 85-127
  { cells: 4, classCount: 1280,
    open: 'ZR4slWRHh7oPmDTpNC68YqshznLmuZBXMVLNWPmxpTk-PPi6yTDnyVbP2okpTo4-GV3Q2q09pGqd9jjn4B8jy_hiburTJ3a-iVzRC-3Nb0SuTarpUVy3JDTXvAFoNbkzu9hz4T7FLXiTPw8psr6gduOORz7toXZK7Fy7UbZ2t2GBdVr9WQ7nOfqjPb74Qc6m9msceEZufONjTP5U6MwpLw' },
  // 768 cells, walks 85-119
  { cells: 4, classCount: 1280,
    open: 'UVbPYSx6I8ybMHGjLE-apO3ItqU1afQMLgtP2VEl2ZqzD8gGT42Pb6Grb_TxwZcpo5Y7erxlyvBWdjTX8EN9sQvRcXND2-VrpyhXmU5XbqTWYHuzVZ3YIoejtIVjPZILV7e6RxrrrNoRuZZXVuUbauN86DU2RbrumC8X5_RKc1FGcY5jt5mu-OPYTdPwm3NW-PNGXaQtuj-NxE4qP52wcw' },
  // 768 cells, walks 84-135
  { cells: 4, classCount: 1280,
    open: 'lNmJ-gAH9kngDPeR6Lwd9uSsnTFz8hObh1Mxi-7TOCuNN0w8hdRWX6GuVB9fq2LM65nrSVS5iS7NK_UWaqZObHhep8yU7DFjFSk9LyPNUY405gzWqTr6BrYKmI3MNjTfZQd4V-JmH5kzTWVdWfbARm1pqNWxo-G6yNTUI-sFP88wI6Opp-UmfKrpuRrzH9BjP1bvsSO0D0VrG6qtdQmtXA' },
  // 1200 cells, walks 111-177
  { cells: 5, classCount: 2080,
    open: 'jxoylVuAWeJTqVVwu1UDos7oIoJzq6TuY1DLMrP6YdSXDXvBuyW1Ubijzsy1PPXc-PgV0XyHldTMWWR1fHLjhkyO0lkt_sA4YiVHpXVk9Ma0xrVBXmhS1ptjzJ_hh92LUb_o6DIVnW0tRs0MZ1VVzSxPlIXpS_04-Jzm1EtmK1ferc6ijo_QHzCq9y4gOfeQuClVeRaZVnBZxlzXVHQJX_EL7JEX-iLutVT-Aq1l7dotMWm0nGO1ab3JZEZcSZ-jZtl7jG603_IcubKNPsoan6I36Zx6jKvTyrjT4JjV16in2kabzXlXpls0Wzb7Kk8dqngv16RV9YXRVG1mmmMdRVWPfko' },
  // 1200 cells, walks 110-162
  { cells: 5, classCount: 2080,
    open: 'wpFZv6waQyzs1svR-RVyxRjq14QDKc2vgWCvoXswy2ldpg-Y6SauaB5JnoLyJlW3WercSGm30vWM2UyrQWfu5TjPc3aJY7aauD6EOpar4uxkzv1OjKX0OaqucQNzrvacvhCo5UdGH_n9gLEYFNNsP8Xgd6ZDmXraUM-yjfY5TWllvMh2Gr5MUodaZnUT9hqGP0JVFNaMWXuh1OLRWl6OOu5YW0IfNX1TzIXvvZgyndSXI2cza37kU2UptVDWJ36LSfjQq6j5A6sSZ3oNbeRLVTB_MyaPHduq4hn_yOctNfSHZLyod8TWaw66H6nFMrU71cowvvhH8dRl1WS7ljaijaX2mdA' },
  // 1200 cells, walks 107-145
  { cells: 5, classCount: 2080,
    open: '4oj5Ko8y0iQa5lF9RPdAya0KbW3sOVToS1-saHne-BDf2IeaUS2VlYlyzJrOUueHXmwr0arNHo4NW0U530vtYCrXws10o_zC6IhbiE5q1to2ZyTdJMRHG7u6knfXw3MYys60tbnPMdVaKXXMNerLB_tlDta1LGeWrydmVqNnh-ucNSsdY4um6KrW8VnhDHrVM6xK5UzZ2UgrUifTF-avoMv1WEtjD90zdLUf4Zpmwc6yjsQ8ftBMzD2dQZ7y03FPcbytO_SK3WyfUJ_yKX5C6x1cdmabdqyqqFXvpOdm4jqpNTXFXsb3lGkz03s1QXuJ22TqtZmEPuK4L6a2kTrWqFvNRlY' },
  // 1200 cells, walks 106-183
  { cells: 5, classCount: 2080,
    open: 'KBrKlN40jSGacOa4SifQtGiNVYO32eLYzBmboq2gv-FVeY8b9JV5pP4O7kHSfNbS1Fz8KJT3BxJnlSNl-zI5jH3anrOMzYMa6Yx_aaRXmBTTrkpUXuzJhJTsQha9D-lOEcs-z3nmFGveZWjlzSYL0bbqOcixP6GX6B2Z-qruJjfGUtfoOTHs12hU_YFe6JOyIz1LmYk62nvwPBcNbVXVzXd0sDOX3It0DH-lkXFGV6BOJ-MaOm6Nau-tTuVcxTjZR_whWDYNlx9HztUQX9X0GRP_1soNLbVmntJLHeoppu4-vpPaOFbu9OiVOI2Pln-owy_ZMHxrsc4y8xzxlj0neJlrFnU' },
  // 1200 cells, walks 105-189
  { cells: 5, classCount: 2080,
    open: 'Z0QK1fo4B2uD6NqbyVTFi0n3pEy31zWY5zrDaLQ1Fm0kbUxmr60KfQ7kyuHB3mGuOhkkNFk65VfFFjjz1ikPaaFzYuV12KekZvWT3ER0iXtJ87FVq8qYpO0y5iPTresw1mtU0sOTzmVWDhatbf0G-QsZdCx-jmKlDL2eSpeTrXtUs9q-wxj9pG5u6aPocRNNvYlQN3uJzbiYzFvI5pNYq5k3qNNSd2BTmabR7HxGuwMe6ylMbbZpoZcSVu8FHbeVNLWrN_IS4_VI98xE1cLaVZgfanHcxOw4jzeaubJRDexOOit3VMumm_SU8Nu0MTBq1jRnmbc9AndfCaKf6tAnXm9kgms' },
  // 1200 cells, walks 97-141
  { cells: 5, classCount: 2080,
    open: 'NGHNymO1hiOcmBtbqBNO0WWTnmTIzr4BbDrnVOqNMEvKWpJP9YQXFZqosvZtEe4deBpxF5y5kL6MaKe6QPc7sDYy5uVzarqsk1K5tpto1qYqt1WPtg1shD-Wxu6Sl9Qm807LOhNTi4faJOHmzxpsuEVplsKc6VmW6aaGrjjF5vheBl0u8l6qzXjcTROHNuhHdi8CVuV4v4uIEjMyeUWzXNOc0SN1LTspMkjvYNXp0bGkx3E7px5l54JWj_BfUh9II-m89hhcHi891ROYifqCrOv4pvHkMF9Ut9pGPoo3Us3G1E6HpD7Mnpo2fJbdyZm21Uer0mp94iB9ZOFsTiqatxIby3s' },
  // 1728 cells, walks 167-234
  { cells: 6, classCount: 3072,
    open: 'ZN0IobYjerPwandyeYbzQWG20loXoamqip61XDEKUGUOvR7Uj6k47Q18Bjh-5Gdkjx29kwe2R7cGtgvh5KjJ5OOs6egjjKbUXG9LDaknkx_Zo2h6jHyRvB2J7ZpsOjp9Tc4e1KZ2CF1fu6YwoFYaZpPlGYWTrLWOtaH56hQyWcuwoZtqHv0ppD5WTz-Mons0zcvhcDDX0bp4PGTGO3KU5rDe5FLGHB-mR-1C-FbD-qXqNE4ZZ13hZNWcxalxbRqzvgStaLdEThqKHt401nE0U0hzphulmZwniO8uIcUz-hplDyP2XBSvcW2Z_BzJuhnJNV22cU6co5RTU1YbX5QrMy1tjps8Gkqr-GaRnox1jaE6xzJp13qMu8TtjUw2Fmi6bJnmGNypHUaTy26ny5Oa1UabPocWOslOZ8tfwiOqcY6ZL1B7x8wmuh2-I5quzhvYClpP70RvZLDZUMnaKaWPob8HQ-2ol4k_odTK-TEkvUZ8x30QNB9j5G11bDR55jt2' },
  // 1728 cells, walks 152-228
  { cells: 6, classCount: 3072,
    open: 'odKWiaohawr7X0CaYdeRSvcOYDyZw3HO0uRjFL1TYuXOo_xUjZJsP8KDOM1_Qp1ek0363QjkOvPw2sdZGt5sFJvGMcXDcmfrWcis1JINTmpxYkg78hpzlYpL083iprON2rypIZ1p_4ywR6YXvaasEA4T_iRvNGqxMlRlb06WksR6Hbf0CG-b3OSUsdb4t-ISY7emtjRsxi2HTVsd1wd4uXaUWszqvSHHlcON1BdxqGP5YzdqpNG-hp32CTOrtpsyMV0vFC8nMevrI2i8uFKSBHnlcWMa48kMtaky_w2yo8gU82egfzO0iQ3Pqi6L6kemM8-ZbMw7cWYp-3sB1omadVYmNG9mNGdKVvNT8KLe5l1x_C5USstKTefH5KaBun4M9jWw1TKfmbml81Rs4lvi9oBNf4_AmwNtPh9KZltuU57KZ4jpZnZs9GlU-eKzuKpDR3Wu_h0Rhq3qUUiedFpTHecX78Qw55xSX-UgjmXb1amBiXPQR7VPgX1k-oR4bIe7' },
  // 1728 cells, walks 140-187
  { cells: 6, classCount: 3072,
    open: 'Hh1UhcMR5uQ6MuE8HUUIcz4NqmK3C-0TYrvqWiG9Kg3tyO6Jzb6QprVSZc-b4YzVmPgnbTN0OI7kgdY1o6qZ5U3GmfdwujgV0-lCmStrbmobRTnuAHJ1Y6bzBtq0rVZtB26TnOYfuSWUejpZjyNvodRROXb4tmujLkUXhkzXk7Mnxru4ukijv6CV5pjvQo67U8HplTui5sWWSGNWT6fKuR7jvRIvQv1RNoma7aM5umXGQDfFyfqLM_XyLFs2eHYOtKX-iFe5RqsHfaOWWwJlx7YRTOk7w5tiT2jTnJsHUvNh2yR2HoeSfIeracekNnqbt9ITLVLtVFbnYxZz8iu0peadwjCJpuvNxrnizsGdqIm4Hwrdr0KW0_ROuvaIfVcib2k7pq7eCo14LYeTbm-NnpJ1hugHV-GRpOcabeOUOm5Okk9maEU1Vp1hVV9HbNqW8B4upfOUtjcpxzzpUVL4mnT5WWu6OPT8Efow0WZmdyhxVOvYZJ8s5xJH9VOI05Gt' },
  // 1728 cells, walks 139-171
  { cells: 6, classCount: 3072,
    open: 'a8nIUbrJqA31mLqSrmWqKdilSksW9YhsD0x7epYhVmSabOrtSKzO6RFZhUuttqWNIlWw0y9nNZSkPw1GM1XXovY3ZcFQ2S8-zKaJWkmntGfRTMOcE8tRuuS0Fjb6hPGN1zeDm6ONckS6nqAybRtDj8NE58ht48xcebSmbiLjE7cj7YVs40p2TqW3IZsWR10vaNZpZmo6nK17NLZVdyrFvkmI9zNZuHvqaNFpDMmzEzhKj1gvpXHK4Cxc2Tp9YG-tCq8OHWtTY2lH3ZSTceVF7oz1N7yhTgKao5qn7opAXnncHZdj6J5hp_Mw_AxTL9GzRnNY06bOWM48qbmWThtWF6QZ5848SqzyfEh-TPol1VjppJy7KNWxYroH8x5qYw81V-jSab-ciipY_Roj_YIZ60HO5ZGn9kqJVuuq5N2M6TJE9d4qPJwqHyeH38nTXCehOTlXjc71QbgsnfMVPeKpsNaSch7mMxnjtWjbcqBOBebsZpmYr1M-qaDdKfk541he' },
  // 1728 cells, walks 136-174
  { cells: 6, classCount: 3072,
    open: 'x0GRqbh5iMwtY0Uix2GzKlVpGF01txFOS9zdQDpcunKcWi3VmqkD5bWwXZ0p_lG-iHn5oj9hNfuKygZ6RyrODTun7OrBUO6ucxjci8RzNHKLFW-KNPy5zfoY6FTsmutOfRNmp9KcyXlIestsGqhtjJFWardo0LYPinIc94tRFOa6cVWy5UqfRq3ZeSfG_D9EHk2Pw0epR6_9Vo1waxbeja6o-1A5Tj1sOgG1ZM-JOf3UJBt1zd5UPYOak3Uau_htQvYUOoetu68MaPiz4NA14dejqhiZqlo1OnulHYRmMvr5UR3LhUm2AZXNuRbUXk6b01SpzkzG3-NVCZFZv5h3huGVEqNb6jwKy8L-S1BpN9MuuVUbm9qI5snU0c_yzTos0nE1j7tEnpWj0dyccyHNmIdWdDu0nHa6FPci3nfIVoczz2N9pHmKVY5j2fgkuMV6hGpe22TyHZWhOo_W0Z1HLzbNU8taXXB21HuRfD7B2BXq6jTHvgU077gfIUfKPmzM' },
  // 1728 cells, walks 133-199
  { cells: 6, classCount: 3072,
    open: 'KIVdp3D0m8kMYTeW3BUcNzWGpiuaOUdJDD8emjxuZ5xRvTJSG6NqdWR0swo51k_TJ6uNg9Wpq5yUce3YY8dmS6Mbc2qDhW_GxyKyadxYrCmKxGa5TtDeVeRcP6itG2uWfppj8HCfKA86F3eTGG6pdW5Ejlg-TrkcBXXzYCjOE9MKV6gdS6V5uT2W6zbU8DPaiZ7Z1vDjsE67oZuhOQ3d44mYq7fAbDLnDjnyK9TUs6XGeaLYOs9Vng69OitDGV7Rbm3WpcL02GOTYV0m7hUU48Fspqg7B8fFOnMYPaq-myjfBJ25K_R01Da52sUo1bE77cqY7kA7Oam_BtrxtAVfjE417Axtu8Jp5OOa0pr16lc46pNpN1JX8g_gK6jaPj-Em8bJ-hqZPNNZKPNkN7XY5ExmbDU-Mm5O2fq_AKcIp811aXLLZbPqcUeV1f9RqOYsL9cPXI7ZRy3rjL1ZK3jc1dOcmsxeziTS-LMT7jEmTJ3Z6Wz0n4X8M1yHPPsuNE7C' },
  // 2352 cells, walks 240-283
  { cells: 7, classCount: 4256,
    open: 'RN2CmkLN842Ud8oZYQRyCUa2a_SjBlR26hhYlbLDoaMOJ-mbRvh8INsWnNbkiNnZUz9WKLK6Ddmdt8Vo85boVzrNxLnPSUqHm00kycYOF5aqXtmCh5bn4pzdbMqom-mcTa9a3FooVeVS7Vi2J9IytrYJa7rmfI5ju_rNzcHSFJ2sJzc9qu05M-Ndg-Z2UreUWzoM-WRwaH8OOs5ztfhMaLZ7TZYrd1xyxDI3XXJUvGXU6UcXm5ZWL1aa_DlHbeLY9VMTiK3bZuWn4uVhixk_V-v-M4FMs7MTu9fCuZvRjPci6QuD8ld1TPOJXdUonPnx_JIOpy_K6HLRdTtbrnPWDd65GWHM8T86csdgIcs-As7eo85kWv14kjLGeFlFRJ-pXJPof4ygNmlExVR-HfKnKZqMOuaz9Do4bT8j2iLmpe68Kqq0_XOAqZ2b7NwFW1vsdG7G1E7tkqvKbXKuWP4HGpfLtylh-WhiabpuzZmH05yys6h3p_nc0bYUefhqtKrs3Z2Gu2yktnNqsdd5HvI2rRqnT0bbr98BmpzNSO1K2qvG053KRo-n3VXAXuNU5_TVqXS0uUCU12vF0PPSOdgKfzET1eehxjOuG9vtkqfvRPZGGi6e7pfvGOsWNr2uRWY6pedyTdGrP1Vsdjr5q-G5tYl41Nv6-rBp43Fwk439lYd6s3oM5jqPR-tsOs16c8jD7nm02g' },
  // 2352 cells, walks 238-289
  { cells: 7, classCount: 4256,
    open: 'RNbmQnTRkMeTe0RuYhFET-YMVdMCS91Fil5SGOmOYWj0UuaT1bDgpF3Q5TNnxwuKWqf2apDaOpsWP47nNmU3pxMr61clPc0a7rqkUadYdSkkbZWJdzRdtxbN7LqHKbJV_edOD18YjFd3DmR3aBkeU-1K8qx4dnKzr83Owngdasqr33g4uLkh6eY0h3YviZesuXyD0KNqWdPODKNNdXrMJm01N61bND2XSnqlAXHaTCM3Yz3fJLJplt4r7Jk5nXbYtZeNfbWk3tylgOPmGO477vi4UJ87Gm9enlF5Nc-G-wmlSPqy9arubgbkOseoeJ58pzM9knT7jPQfEefcWhmvUM1q7jS5ONfmJE10O5QuU87sfyzS1mHnOi2M2hZEdum6zmFofw2WfInEFB7nlUqqTZMbGrmc0cze5_WIiKltLyVtu81h2rmZjht0x9yltVpZyXT7U-ZoV5qt6TF5mt5SsYbPw0cq5pTGPweY6hkZN5c9WHHG2qxo7xqjktNcW-B701nHyzVnzh0K67kt47qheF8Xuh10fyZOxm6OMWY-J7ZxPIpq9eUdxnDGeTnlamp1vaVjOMptuVVN46yp1ediHzUO67JZecykTrfZztT9RuYWks70SpWuauYVr3JqGF08da_pGMfUzcqWZ4j7gmjdaXqjA_Pn3D-D7FRzqp8Dvh5n1XketwLOusfczFr7YmaO2no0rQ' },
  // 2352 cells, walks 232-291
  { cells: 7, classCount: 4256,
    open: 'ZHJGmUeqqWaRY8wbMRVlGMauVmWgdMw0rkxDFjo-NeoPVToqRoyfVlmK9Bw9vKPsIh-3KvLomJuX0cluPmae2kVrP1NDbU-Zp0SzBW5soeMl59FqlKGvwzvmrikZr2mW7td0OHM_M6oD8WSzZtOCchG71bGk3j2rSf3UaVK5y_WPU6o59V9B5cq0cXFdUy6p4wCWbu5YmOnEFzb5udH5cnFCzXGe0rHGyHZXiHiy2Sla2s9BZvpx49qmvJl9c-lrBmbpU8P7PEZ5z94GoPd0eXbeTBzNup6Ty9Ktpx0568mwlE73X8hzLa0SHzXVbrFwe_QMbz4p2C7cdO7UNadOk7adzgXbXN7ERxc5eeiyKlWvpXqOWdmWqTejDklV_KwyLF3eIdomblRQ05uG9dWIFjF7FL2LrFKPnzFkU3-devxmTD4s26R5PjYtzXNmefR4IY_fXjqmnTtCm_k6-TR08kPvwusOxpljxvvqUukSMbJ7Wdqm6MfZ2rSY2twnZ4jaPXMz3g8oWro7rNc9Jjor76Sn1h1zz8TsQjUlaVTV5cbUaRrNnM45dLEj3z4tz4qWbizV7hydp2txUZuSm81K-DZ_XXhMRtypH75zd5aL9J0M5LUuX5bXZly3mHj4atzj9TPVIdVbmlwf7FX-UGlX9qBY16Z1vmmxGrv4TijVP3nY4-ouQaY2216T5dNHae-J08zjqg' },
  // 2352 cells, walks 214-273
  { cells: 7, classCount: 4256,
    open: 'YspkbNPOELJZx8THAxnE2WDUMq2jpQ2jLF5LEG1adfizQeYpmxnhtsioTo6rbF1Ub5zNiTJmf6xG5mPTddyWNXPbmWoG6dg710g0Yqg2ZVy614XQyTY3s59HHi37SrCfTqUddTchfT3HsMmIRoMWzdi8m4zS1nvD2fzeRJrO5qTbXLo_htOnI6nS3HRX2uQs8syIlc8HKX8kNG05_WxMT06Y1rYztlhwwHp1otMDOTPW98EszdHtjpmYW6YdvfI_RQr5e3XkRR1rm9WseleM-m1WyaN1OmtTi-2bh0_Ho2kdY7PWwj996EjjaqfqC_Fy2uZA4eZZWzo431Fu9yuFZD0ZNmc5-5JZ1cvHQyN1VL1fde55ioz4zEN3WtBVtDqJ_ox4PHamMWYxcacOhaONPtnYrTky96zOJXSYtG528M9sMO3wHOnNqxk9_wKU48pcK_w9KiWP6u7S2yiMXJtXOrLcopqatSXKNi-kHW2ls3FlxtOLzXesT-ameJvJ6OnN1qbdtMFzlGu2_-CjejhSbXefKaF9W2fel4SzevFDqMfXDFyvxLE5K6zSf2l5THazs-KYjOzhF5Njxz0ftnOh2dc9QjSfUdydN5w-OuvqldHHQy2ub-r0zjOrmFubjuB6sW21g26kW1eazGr66M7PQfT0dAxvdT23FN6JTFnT7XsH8pm4I2tnculqXTSn54-WHmjnGw' },
  // 2352 cells, walks 208-285
  { cells: 7, classCount: 4256,
    open: 'Ykug2C5pozk8h8JpxhVm0wIQ3dmodExejDpSVXGdqI6SMX64-LTD0JWd9lXfCsRu5flbAHr7EcQ0u6hefn8D1jS0MdcVi1kZnU-kfMlh0jSxy9SIx6l3ah_ivFjOa5czq21mkX1VDI171dA3Zd6kJpcxbVvbmbhIOjdG3e70etDmNmx61noEcmVHpy3nWoLhbs6yCOOsWhZWMWuNm0enKnlV3wzWVFl1xo8HNPXDwUdZ13SPozZ8ppaytj81-ZhMt7E8JjzzjxKmeeVx0ltFdZtXdXpRvfcMjN_D47H0lLBOl9-TZK9y8vCkKtTe89o2RNYlNVaX1aOK1qy2vw241Fa1eLH1ZO6akfPla4FDOr_NTqOamo7eVdjOR0NRqJdz1EzbqOaBqhp2VJZenmHo5WA50vYTp32Ffdw8HHrbWM20k1ubV8Mcb5Ot6zitC3xHiLFl-91RMtvOtqkYrr0PhTmk2212h8BZtxZpzovp1OxmI49K9-nR8dZ0kow3Npe9jos5nikdztSuHXZPU8ZzjUlzj1q---iOho6Vx4Pp6j2vuONMMyqxPnLpE1bHsuw9G5xWk-OUU0TVcxUfqv4VU3k6wnprmV1OhsveqA_fNYvQVy7tHzXfVwTXdFzhtpubud2kXB7NnLGof0-HauPQynNYIvzWHLtOKnXMXtOx3mr_DnkjeT6qkumcc1rbRpcOXvdnEw' },
  // 2352 cells, walks 203-291
  { cells: 7, classCount: 4256,
    open: 'Btd0BlJnGrrNDS5VBwWu0-C0R7KhkIn3jARRle2LiQe8x46ZnFj2UNHGTHYPw1PzGvtlLHisQ7YfTdKdudXFTrnThb4p43c1qF0kZczxMQebS5-jLBSvdF43aulblx0ke2PlRVqrix5DzWw1bxil5taUl8lP7WBdt6n615DkfsJuD007rVW2Fb8WnEVfC6JZqVwduXpDOR80lMfRrW5fA2Kq7douvVHR5hxDhZpVvmZ4My2ttw-dhyHVmrsO9bOgjes546IvpmucY3dujrpja2lTa5viZ9NKxw6_3VmdTE7HPk23yGfM0ZGUtqj-vLIUVtRkPG49asaj99mKaBrzNfk_pGd1En7hri2FJm2707mxXqj3GZLPZF1paVxUXDxZpn74Yoj_iyCRUV6qJXebBui7KmEqu7od0LnufM9gatVjn88Ik7rMdyX3-Wo0tjetcSly1ZuvI_5oaUo8fwpdw2NtcjVuyWHqJwsZuvKYM8c6n1XJubXm-BfVI1b7yIz1K2-uO2PIxqVubmHtSvkjmW1ymuY_mmfPXPOqWnKpuDM9NzmrmK2S_Zkw-rN8JM7OVF30KtVZWO8olzM65uXH0e1t4zkzZqNJnds89rY0mul54tSLvofH04nzkHQ5dwzekTysV35yTMe5wab2sOhrl4zY5szd1E2De9Rq13LWR9fbg6pWG6V7VTk0szlYx1WnXvi2pg' },
];

/** The rulings there are designs for, in the order the page should offer them. */
export const INFINITY_CUBE_RULINGS: readonly number[] =
  [...new Set(INFINITY_CUBE_DESIGNS.map(d => d.cells))].sort((a, b) => a - b);

export function infinityCubeDesigns(cells: number): readonly StoredDesign[] {
  return INFINITY_CUBE_DESIGNS.filter(design => design.cells === cells);
}
