/**
 * The mazes the folding page shows — found offline, kept here.
 *
 * GENERATED by `.dev/probe-fold-designs.ts`. Do not edit: run the probe.
 *
 * The object never varies, so neither do these. A search takes seconds at
 * three cells across a face and the better part of half a minute at four,
 * which is not a wait to put in front of someone who opened a page; found
 * once, they cost a decode and a check. They are the best of sixteen tries at
 * each ruling, ranked by the longest walk in the pose where it is shortest —
 * see the probe for why that is the measure.
 *
 * Each is a perfect maze in all six poses. The page checks that again as it
 * decodes, because a stored design is only as good as the surface it was found
 * on, and falls back to searching if it ever stops being true.
 */

import type { StoredDesign } from '../stored-design.ts';

export const INFINITY_CUBE_DESIGNS: readonly StoredDesign[] = [
  // 192 cells, walks 44-56
  { cells: 2, classCount: 272,
    open: '3MRdI4KNZlatrmlCmQ_HHnzl1mg-LnBly6nNd9jV4167vQ' },
  // 192 cells, walks 39-53
  { cells: 2, classCount: 272,
    open: 'LkguPazjWmcVdZvyTNpgUp2x061xDt7tgFprJjm7unuHTg' },
  // 192 cells, walks 38-56
  { cells: 2, classCount: 272,
    open: 'LfkaljJW66Cl8tVl6Afert3RlKU9Zur1nl95LsnS6hreWg' },
  // 192 cells, walks 38-50
  { cells: 2, classCount: 272,
    open: 'xSVqPq8WQpXb8YpTi06sfkPrcD9EVJxRe7PJE6PTZLnFxw' },
  // 192 cells, walks 37-46
  { cells: 2, classCount: 272,
    open: 'A-sK7S5MLc4WnNknOcua6ey3x01OWRalRFuXzqu3mN43Jw' },
  // 192 cells, walks 37-51
  { cells: 2, classCount: 272,
    open: '2EPUx2qajttmmHJJnWw6lHiY6XdhJqATatOePlpvz2mNWg' },
  // 432 cells, walks 67-91
  { cells: 3, classCount: 696,
    open: 'jmhgPqgz1lzJ2ZorSnXo9IT8GaKmOdrlsWx0RrHaPyZpGz3rlL11KXO5F1eCMZ8R6bI5Gl1sQdmefC5rqj7ajY6R9GI9MNW3OZ-NOd_SGzeLPp01Na3P' },
  // 432 cells, walks 67-80
  { cells: 3, classCount: 696,
    open: 'o049onZjxg1quKaaaUYtLL2ic73KnNSaS66oQhdpoyZ3dk7lTw_rLLuU3OBnlbbCOzJi2q1Xm5PB-uyzFlID9XBPcq0fn3ma-bSYL5FHUz01Y1lt6nzI' },
  // 432 cells, walks 64-95
  { cells: 3, classCount: 696,
    open: 'pK4SejhQnS-yzthVi49QGTubHeXGuF2q8-bRNtNG7VnXVLS5gcvnwzqJZk4fZS1VOSfsHGedjhusS0PbxYNjrXCG2tZ-aadtZCYuLzZuuGVdTc_yzhPb' },
  // 432 cells, walks 63-87
  { cells: 3, classCount: 696,
    open: 'wnVjWFPPU1FtzOJwLmbdKKG5icPzSL-Jo1D6FcM2qg9T1-qdK3LQJTdk8jN5pgey5DI545xcvL0jnZZELt753MmO-MnLIjFfhkxPbHcXh-ZSpR70La3B' },
  // 432 cells, walks 61-76
  { cells: 3, classCount: 696,
    open: 'VAd_TuJHo47YsVTxPaMuFZqGTH2JMp9BukU2LbkYeuVtznS28qMdXhtzevOhaNbk0tSsE_lYffCwfFqeM-cj-pzVWd2kmRHtS6Vpcd3lFq1qsTp8HOwn' },
  // 432 cells, walks 61-84
  { cells: 3, classCount: 696,
    open: 'bYKV3MQ2PIZJ9jF10suFypVr_VQynOR0c4Mqvr0uZwq75ZMiJ7qqGJdGw1Va0uPDwszoNA4nGnnTHhumnFjVjpzgmzujqR5VHcaWWVlOm4HtcV6xusny' },
  // 768 cells, walks 104-117
  { cells: 4, classCount: 1312,
    open: 'z0W4fUXkOW7BVPwCpg6czNAmpFcdWTbHGW4HjESWHs4Qn5mpYlw7cl51LuGS9VTU3bBny-WnVpNdUJlOR6qWblnOtTNP1aTjkdBni666a3Yfjy06SlUVt2qKedCpEuXkFTt5sOoj0ZrViTubVtODxitDxV1HPi9J-lWVL_bCXbRxfUU6lb7S6pEvMM74MsZaqtmcDo93pcOx8Rv59iDs0E1O66U' },
  // 768 cells, walks 99-122
  { cells: 4, classCount: 1312,
    open: 'VKZayJGy2OO4NGydYN0hw56zcE7OU75qbS9WCTR-D-6lGZU8odyapbEqP65JP1PcaNiavRumouYO3leaBbonGw70MVM60TwRuWyOaD85bVMd2PhZUo7eNN0oY-5gVTc-Edln6x7a08JjMB9tMnrOc4gaXTexLll84oxarrW1xecxpvKmhpWe5HML_qCWXcE7zLg7_MhXsq60Nae14TkdszprIKU' },
  // 768 cells, walks 88-122
  { cells: 4, classCount: 1312,
    open: 'J8R6ljGW8TG8Fv4uOcyjQd_DQ3xBp0F5bcJ74fAhzZiebpGtjjmUR1gvI051aHF6jjGjOWZlraG8Zj7l8sitDo2TRydapjIzPzos7WZN58hhRj-W5YXlmiZ90o5oVOeYjVM2X7Y1OUGPT0VrXkJNUYt_QSabrU6MXo2al7OfDhPXsF0_EmWOqp9N6ZJN2KjYMfZ_tIrZRjd68ahIWa_QdvRL7MU' },
  // 768 cells, walks 86-112
  { cells: 4, classCount: 1312,
    open: '1HIXM2pKNupGFSuQnyTmpNYbF6zywy3iiSWvIq1XxZxkbxzIujhVU-qyXSXbx4bai6zi4EW7Q7lyluOcMWU32qW2bH5QPWtmxzUbaHvUNR5XOzmlNUfbn5I4Z5HeGadZQzw7pK9hbiWfbY1tu06l1EPYJdH5U5c1OpeXZNSd6CfG2TKZjZGlPa1jlDNssXp6hZfZpnqamdPmcqZnDeNr0szjcY4' },
  // 768 cells, walks 80-125
  { cells: 4, classCount: 1312,
    open: 'plGL9agUM6OGM3BqSrcl9ZIud6aj0eiXXi4hXbw-djCvxqAaPTdsssVurjWa-jI7E-GVvjyh3FNKh2rqkTOWybis7qnbuBPfktI5atXwMWfWzs6WB3v0oWkYfeMkasXYq1bejcRN06JVmjKuzhrfOvFtQKO28jemGSVP7Slu4TdesFnvElslOX6itatGfbIGq7fpNxrjXHancexHbWlpd-BZnpo' },
  // 768 cells, walks 79-94
  { cells: 4, classCount: 1312,
    open: 'wvK0x2VS5TXaJD9kk4nkdDSir1jHdk12llLWRrAryis661JfYyw595U2jsZG9tJkWtWk0aHPrWDZ4CU1PLeGpwem2tapdjM6sRnapydHE-W4h1YdvSFfOnhImai9gtWU51NshXfxldbsMbuKVW-JPEv3pHdxG2oZyTdLNEquVKW6i46Wjid7GJsBXTaiX1xpT4teDV2z7NO53MVrSGzN3IJojY8' },
];

/** The rulings there are designs for, in the order the page should offer them. */
export const INFINITY_CUBE_RULINGS: readonly number[] =
  [...new Set(INFINITY_CUBE_DESIGNS.map(d => d.cells))].sort((a, b) => a - b);

export function infinityCubeDesigns(cells: number): readonly StoredDesign[] {
  return INFINITY_CUBE_DESIGNS.filter(design => design.cells === cells);
}
