/**
 * The mazes the folding page shows — found offline, kept here.
 *
 * GENERATED by `.dev/probe-fold-designs.ts`. Do not edit: run the probe.
 *
 * The object never varies, so neither do these. A search takes seconds at
 * three cells across a face and the better part of half a minute at four,
 * which is not a wait to put in front of someone who opened a page; found
 * once, they cost a decode and a check. They are the best of two dozen tries at
 * each ruling, ranked by the longest walk in the pose where it is shortest —
 * see the probe for why that is the measure.
 *
 * Found under the welding rule a builder needs rather than the one a walk
 * needs: a side buried against another cube agrees with whatever is on show on
 * top of it (`BuildSurfaceOptions.weld`), so no printed wall can ever peek
 * across a passage on the model.
 *
 * Each is a perfect maze in all six poses. The page checks that again as it
 * decodes, because a stored design is only as good as the surface it was found
 * on, and falls back to searching if it ever stops being true.
 */

import type { StoredDesign } from '../stored-design.ts';

export const INFINITY_CUBE_DESIGNS: readonly StoredDesign[] = [
  // 192 cells, walks 43-55
  { cells: 2, classCount: 256,
    open: '5XOg5UNL4mmqlpexqbvlnXExE4-h-enYLl1Xpe7SKls' },
  // 192 cells, walks 40-51
  { cells: 2, classCount: 256,
    open: 'FlWvNoKuKq50-b6kpLNGYXk0XJGqtVnetOWJMb1O2t4' },
  // 192 cells, walks 40-49
  { cells: 2, classCount: 256,
    open: 'TFRsNrhubblj9ZZGL6DM6rBtd-fiYoTMknkeuXYbsec' },
  // 192 cells, walks 40-51
  { cells: 2, classCount: 256,
    open: 'lEZcY9TlRu-qrY50xIbb6s6KnBkXzhnPrtDFXtfuzOc' },
  // 192 cells, walks 39-65
  { cells: 2, classCount: 256,
    open: '1FOi9Baec2V2ntmAI3Hdjp3LjqnnVR_L-IgmUutt4ck' },
  // 192 cells, walks 39-54
  { cells: 2, classCount: 256,
    open: 'ZUGscuy25WlWHV_FCWW-k-XchlhLpcbh-qU13u7epxk' },
  // 432 cells, walks 69-84
  { cells: 3, classCount: 672,
    open: 'dguKQ1dqbS0g5hbbWt41VdK500wxVvmJ1xGPgr4Mz3RfjpYje7PFbKacKjqrNzo6jXjg0uz4aQTp9mBEu5wby5vH4T6Nx6aXdElzuMZhuRPLjvEs' },
  // 432 cells, walks 66-91
  { cells: 3, classCount: 672,
    open: 'auSipg3DV4a3tEo7RbniHK5NSs56xrims6p6NbeYk9qWbPZo61gsx6qszD4-WnM4rYSf0ZpltjQbi1XV1p4zfmZ7jop6Jpe2XVOfz3M-sSOdVa22' },
  // 432 cells, walks 65-83
  { cells: 3, classCount: 672,
    open: 'lGk2I7TSFTvJzzBvYdsi1Y1vXDgTZmp0E5tcBl1c3DPXs9-c8nxsylXquPXReeOU6isdczab57Jipa60zJ6ZbQ_uUUkOWe50N3pmZmxqXirmTHkY' },
  // 432 cells, walks 65-92
  { cells: 3, classCount: 672,
    open: 'cXiyHsUTX8hbaqroWmMhN-HD7WJkY-El9iHOGhzPjFazEpe3ppm53mfGbVye5egkXbiqVLY6djh3u8TOjviI52YST5xZxefk9aj02X2Xde7M4elo' },
  // 432 cells, walks 63-80
  { cells: 3, classCount: 672,
    open: 'NmJNayTakdRS-lRVm8xs4T-8Sut47KOoM3rE1pRZBcTqYx47s3XO1G_h5caOqcIdDjsr2egmjzSnC9d72p7h6KvbNFYFhWKTtOnV7nGUz7JZZ66n' },
  // 432 cells, walks 63-87
  { cells: 3, classCount: 672,
    open: '3iFZzGQ2Ql226tFysfWVuDU50DIan22PAVO3pSV-4KFlVxuXnkYnC3daoxd5K1qWRsbqME48jLesiw5V2YubL9N5zMxwdlrssAW3rAO3NH5JN67b' },
  // 768 cells, walks 96-136
  { cells: 4, classCount: 1280,
    open: 'FnWZNxHE90ngFFqPYVUi07ODWvtTadtNKzB212xdUR8XHWajdeJxVF_j2qF5mWQ9SWldZI27Ck0lr9hbnTzXZlY5K67JrGnuRXRLi_K1FfW0NYM7WjPqPZrOlzSKlm1FTwdnbVjfmDc5i1jvC9A92Rta7Z1Urm7Lmlfo5Uh7grFHvHblbHaW8H5B-FrT8TV6aluT8mHV1mnz0r2YwVNtBw' },
  // 768 cells, walks 87-108
  { cells: 4, classCount: 1280,
    open: '5QFXcg7ORgaekippeM2nNcYbY_9gjpy2L2vEY35jI3OMo1oaOHOb9D6sH9psnmiXjZixO7I5RD9bi9rTOyu8yRqpXK-5K2Y_esAnz5nCFesfKTtyk5rlHXnau0SHTuNWrJ9AmnkRdscjPmqZOeUdPXamK3IlrZnskfLumKZ4Oq_yKZfKB5GmWtW1cbG15bVY7Y1jyc2OrtcZadWf8I2qRQ' },
  // 768 cells, walks 86-112
  { cells: 4, classCount: 1280,
    open: 'xx5GMHk1RsVWMJk0Lm481GYrrll8feFaO1G7XOEeNjE0jNacNd3VBzqp_AldjvPDHBx_ODmKd4hae8reefBM7clqWz-XlaX0U_DDCpttuWnNKkun36JWNu4KpYMVt8lgpVq1R-p6dctloY4bluQHnLgy2_zIJpvOfsyIdiar3Bp40lzGWtiawZlZeTqL7eQbbr7oOM4vc_dQg5yusVfmCw' },
  // 768 cells, walks 85-127
  { cells: 4, classCount: 1280,
    open: 'ZR4slWRHh7oPmDTpNC68YqshznLmuZBXMVLNWPmxpTk-PPi6yTDnyVbP2okpTo4-GV3Q2q09pGqd9jjn4B8jy_hiburTJ3a-iVzRC-3Nb0SuTarpUVy3JDTXvAFoNbkzu9hz4T7FLXiTPw8psr6gduOORz7toXZK7Fy7UbZ2t2GBdVr9WQ7nOfqjPb74Qc6m9msceEZufONjTP5U6MwpLw' },
  // 768 cells, walks 85-119
  { cells: 4, classCount: 1280,
    open: 'UVbPYSx6I8ybMHGjLE-apO3ItqU1afQMLgtP2VEl2ZqzD8gGT42Pb6Grb_TxwZcpo5Y7erxlyvBWdjTX8EN9sQvRcXND2-VrpyhXmU5XbqTWYHuzVZ3YIoejtIVjPZILV7e6RxrrrNoRuZZXVuUbauN86DU2RbrumC8X5_RKc1FGcY5jt5mu-OPYTdPwm3NW-PNGXaQtuj-NxE4qP52wcw' },
  // 768 cells, walks 84-135
  { cells: 4, classCount: 1280,
    open: 'lNmJ-gAH9kngDPeR6Lwd9uSsnTFz8hObh1Mxi-7TOCuNN0w8hdRWX6GuVB9fq2LM65nrSVS5iS7NK_UWaqZObHhep8yU7DFjFSk9LyPNUY405gzWqTr6BrYKmI3MNjTfZQd4V-JmH5kzTWVdWfbARm1pqNWxo-G6yNTUI-sFP88wI6Opp-UmfKrpuRrzH9BjP1bvsSO0D0VrG6qtdQmtXA' },
];

/** The rulings there are designs for, in the order the page should offer them. */
export const INFINITY_CUBE_RULINGS: readonly number[] =
  [...new Set(INFINITY_CUBE_DESIGNS.map(d => d.cells))].sort((a, b) => a - b);

export function infinityCubeDesigns(cells: number): readonly StoredDesign[] {
  return INFINITY_CUBE_DESIGNS.filter(design => design.cells === cells);
}
